import Ember from 'ember';

export default Ember.Component.extend({
  classNames: ['flag-icon'],
  attributeBindings: ['title'],
  
  title: Ember.computed('country',function(){
    return this.get('country.name');
  }),
  
  setup: Ember.on('didRender',function(){
    
    let country = this.get('country');
    
    if(country){
      let iso = country.get('id').toLowerCase();
      let url = this.get('flagPaths.'+iso);
      this.$().css({
        'background-image': 'url('+url+')',
      });
      this.$().show();
    } else {
      this.$().hide();
    }
    
    if(this.get('size')==='big'){
      this.$().addClass('flag-icon-big');
    }
    if(this.get('size')==='medium'){
      this.$().addClass('flag-icon-medium');
    }
    
  }),
  
  flagPaths: {
    ad: 'assets/images/flags/4x3/ad.svg',
    ae: 'assets/images/flags/4x3/ae.svg',
    af: 'assets/images/flags/4x3/af.svg',
    ag: 'assets/images/flags/4x3/ag.svg',
    ai: 'assets/images/flags/4x3/ai.svg',
    al: 'assets/images/flags/4x3/al.svg',
    am: 'assets/images/flags/4x3/am.svg',
    ao: 'assets/images/flags/4x3/ao.svg',
    aq: 'assets/images/flags/4x3/aq.svg',
    ar: 'assets/images/flags/4x3/ar.svg',
    as: 'assets/images/flags/4x3/as.svg',
    at: 'assets/images/flags/4x3/at.svg',
    au: 'assets/images/flags/4x3/au.svg',
    aw: 'assets/images/flags/4x3/aw.svg',
    ax: 'assets/images/flags/4x3/ax.svg',
    az: 'assets/images/flags/4x3/az.svg',
    ba: 'assets/images/flags/4x3/ba.svg',
    bb: 'assets/images/flags/4x3/bb.svg',
    bd: 'assets/images/flags/4x3/bd.svg',
    be: 'assets/images/flags/4x3/be.svg',
    bf: 'assets/images/flags/4x3/bf.svg',
    bg: 'assets/images/flags/4x3/bg.svg',
    bh: 'assets/images/flags/4x3/bh.svg',
    bi: 'assets/images/flags/4x3/bi.svg',
    bj: 'assets/images/flags/4x3/bj.svg',
    bl: 'assets/images/flags/4x3/bl.svg',
    bm: 'assets/images/flags/4x3/bm.svg',
    bn: 'assets/images/flags/4x3/bn.svg',
    bo: 'assets/images/flags/4x3/bo.svg',
    bq: 'assets/images/flags/4x3/bq.svg',
    br: 'assets/images/flags/4x3/br.svg',
    bs: 'assets/images/flags/4x3/bs.svg',
    bt: 'assets/images/flags/4x3/bt.svg',
    bv: 'assets/images/flags/4x3/bv.svg',
    bw: 'assets/images/flags/4x3/bw.svg',
    by: 'assets/images/flags/4x3/by.svg',
    bz: 'assets/images/flags/4x3/bz.svg',
    ca: 'assets/images/flags/4x3/ca.svg',
    cc: 'assets/images/flags/4x3/cc.svg',
    cd: 'assets/images/flags/4x3/cd.svg',
    cf: 'assets/images/flags/4x3/cf.svg',
    cg: 'assets/images/flags/4x3/cg.svg',
    ch: 'assets/images/flags/4x3/ch.svg',
    ci: 'assets/images/flags/4x3/ci.svg',
    ck: 'assets/images/flags/4x3/ck.svg',
    cl: 'assets/images/flags/4x3/cl.svg',
    cm: 'assets/images/flags/4x3/cm.svg',
    cn: 'assets/images/flags/4x3/cn.svg',
    co: 'assets/images/flags/4x3/co.svg',
    cr: 'assets/images/flags/4x3/cr.svg',
    cu: 'assets/images/flags/4x3/cu.svg',
    cv: 'assets/images/flags/4x3/cv.svg',
    cw: 'assets/images/flags/4x3/cw.svg',
    cx: 'assets/images/flags/4x3/cx.svg',
    cy: 'assets/images/flags/4x3/cy.svg',
    cz: 'assets/images/flags/4x3/cz.svg',
    de: 'assets/images/flags/4x3/de.svg',
    dj: 'assets/images/flags/4x3/dj.svg',
    dk: 'assets/images/flags/4x3/dk.svg',
    dm: 'assets/images/flags/4x3/dm.svg',
    do: 'assets/images/flags/4x3/do.svg',
    dz: 'assets/images/flags/4x3/dz.svg',
    ec: 'assets/images/flags/4x3/ec.svg',
    ee: 'assets/images/flags/4x3/ee.svg',
    eg: 'assets/images/flags/4x3/eg.svg',
    eh: 'assets/images/flags/4x3/eh.svg',
    en: 'assets/images/flags/4x3/en.svg',
    er: 'assets/images/flags/4x3/er.svg',
    es: 'assets/images/flags/4x3/es.svg',
    et: 'assets/images/flags/4x3/et.svg',
    eu: 'assets/images/flags/4x3/eu.svg',
    fi: 'assets/images/flags/4x3/fi.svg',
    fj: 'assets/images/flags/4x3/fj.svg',
    fk: 'assets/images/flags/4x3/fk.svg',
    fm: 'assets/images/flags/4x3/fm.svg',
    fo: 'assets/images/flags/4x3/fo.svg',
    fr: 'assets/images/flags/4x3/fr.svg',
    ga: 'assets/images/flags/4x3/ga.svg',
    gb: 'assets/images/flags/4x3/gb.svg',
    gd: 'assets/images/flags/4x3/gd.svg',
    ge: 'assets/images/flags/4x3/ge.svg',
    gf: 'assets/images/flags/4x3/gf.svg',
    gg: 'assets/images/flags/4x3/gg.svg',
    gh: 'assets/images/flags/4x3/gh.svg',
    gi: 'assets/images/flags/4x3/gi.svg',
    gl: 'assets/images/flags/4x3/gl.svg',
    gm: 'assets/images/flags/4x3/gm.svg',
    gn: 'assets/images/flags/4x3/gn.svg',
    gp: 'assets/images/flags/4x3/gp.svg',
    gq: 'assets/images/flags/4x3/gq.svg',
    gr: 'assets/images/flags/4x3/gr.svg',
    gs: 'assets/images/flags/4x3/gs.svg',
    gt: 'assets/images/flags/4x3/gt.svg',
    gu: 'assets/images/flags/4x3/gu.svg',
    gw: 'assets/images/flags/4x3/gw.svg',
    gy: 'assets/images/flags/4x3/gy.svg',
    hk: 'assets/images/flags/4x3/hk.svg',
    hm: 'assets/images/flags/4x3/hm.svg',
    hn: 'assets/images/flags/4x3/hn.svg',
    hr: 'assets/images/flags/4x3/hr.svg',
    ht: 'assets/images/flags/4x3/ht.svg',
    hu: 'assets/images/flags/4x3/hu.svg',
    id: 'assets/images/flags/4x3/id.svg',
    ie: 'assets/images/flags/4x3/ie.svg',
    il: 'assets/images/flags/4x3/il.svg',
    im: 'assets/images/flags/4x3/im.svg',
    in: 'assets/images/flags/4x3/in.svg',
    io: 'assets/images/flags/4x3/io.svg',
    iq: 'assets/images/flags/4x3/iq.svg',
    ir: 'assets/images/flags/4x3/ir.svg',
    is: 'assets/images/flags/4x3/is.svg',
    it: 'assets/images/flags/4x3/it.svg',
    je: 'assets/images/flags/4x3/je.svg',
    jm: 'assets/images/flags/4x3/jm.svg',
    jo: 'assets/images/flags/4x3/jo.svg',
    jp: 'assets/images/flags/4x3/jp.svg',
    ke: 'assets/images/flags/4x3/ke.svg',
    kg: 'assets/images/flags/4x3/kg.svg',
    kh: 'assets/images/flags/4x3/kh.svg',
    ki: 'assets/images/flags/4x3/ki.svg',
    km: 'assets/images/flags/4x3/km.svg',
    kn: 'assets/images/flags/4x3/kn.svg',
    kp: 'assets/images/flags/4x3/kp.svg',
    kr: 'assets/images/flags/4x3/kr.svg',
    kw: 'assets/images/flags/4x3/kw.svg',
    ky: 'assets/images/flags/4x3/ky.svg',
    kz: 'assets/images/flags/4x3/kz.svg',
    la: 'assets/images/flags/4x3/la.svg',
    lb: 'assets/images/flags/4x3/lb.svg',
    lc: 'assets/images/flags/4x3/lc.svg',
    li: 'assets/images/flags/4x3/li.svg',
    lk: 'assets/images/flags/4x3/lk.svg',
    lr: 'assets/images/flags/4x3/lr.svg',
    ls: 'assets/images/flags/4x3/ls.svg',
    lt: 'assets/images/flags/4x3/lt.svg',
    lu: 'assets/images/flags/4x3/lu.svg',
    lv: 'assets/images/flags/4x3/lv.svg',
    ly: 'assets/images/flags/4x3/ly.svg',
    ma: 'assets/images/flags/4x3/ma.svg',
    mc: 'assets/images/flags/4x3/mc.svg',
    md: 'assets/images/flags/4x3/md.svg',
    me: 'assets/images/flags/4x3/me.svg',
    mf: 'assets/images/flags/4x3/mf.svg',
    mg: 'assets/images/flags/4x3/mg.svg',
    mh: 'assets/images/flags/4x3/mh.svg',
    mk: 'assets/images/flags/4x3/mk.svg',
    ml: 'assets/images/flags/4x3/ml.svg',
    mm: 'assets/images/flags/4x3/mm.svg',
    mn: 'assets/images/flags/4x3/mn.svg',
    mo: 'assets/images/flags/4x3/mo.svg',
    mp: 'assets/images/flags/4x3/mp.svg',
    mq: 'assets/images/flags/4x3/mq.svg',
    mr: 'assets/images/flags/4x3/mr.svg',
    ms: 'assets/images/flags/4x3/ms.svg',
    mt: 'assets/images/flags/4x3/mt.svg',
    mu: 'assets/images/flags/4x3/mu.svg',
    mv: 'assets/images/flags/4x3/mv.svg',
    mw: 'assets/images/flags/4x3/mw.svg',
    mx: 'assets/images/flags/4x3/mx.svg',
    my: 'assets/images/flags/4x3/my.svg',
    mz: 'assets/images/flags/4x3/mz.svg',
    na: 'assets/images/flags/4x3/na.svg',
    nc: 'assets/images/flags/4x3/nc.svg',
    ne: 'assets/images/flags/4x3/ne.svg',
    nf: 'assets/images/flags/4x3/nf.svg',
    ng: 'assets/images/flags/4x3/ng.svg',
    ni: 'assets/images/flags/4x3/ni.svg',
    nl: 'assets/images/flags/4x3/nl.svg',
    no: 'assets/images/flags/4x3/no.svg',
    np: 'assets/images/flags/4x3/np.svg',
    nr: 'assets/images/flags/4x3/nr.svg',
    nu: 'assets/images/flags/4x3/nu.svg',
    nz: 'assets/images/flags/4x3/nz.svg',
    om: 'assets/images/flags/4x3/om.svg',
    pa: 'assets/images/flags/4x3/pa.svg',
    pe: 'assets/images/flags/4x3/pe.svg',
    pf: 'assets/images/flags/4x3/pf.svg',
    pg: 'assets/images/flags/4x3/pg.svg',
    ph: 'assets/images/flags/4x3/ph.svg',
    pi: 'assets/images/flags/4x3/pi.svg',
    pk: 'assets/images/flags/4x3/pk.svg',
    pl: 'assets/images/flags/4x3/pl.svg',
    pm: 'assets/images/flags/4x3/pm.svg',
    pn: 'assets/images/flags/4x3/pn.svg',
    pr: 'assets/images/flags/4x3/pr.svg',
    ps: 'assets/images/flags/4x3/ps.svg',
    pt: 'assets/images/flags/4x3/pt.svg',
    pw: 'assets/images/flags/4x3/pw.svg',
    py: 'assets/images/flags/4x3/py.svg',
    qa: 'assets/images/flags/4x3/qa.svg',
    re: 'assets/images/flags/4x3/re.svg',
    ro: 'assets/images/flags/4x3/ro.svg',
    rs: 'assets/images/flags/4x3/rs.svg',
    ru: 'assets/images/flags/4x3/ru.svg',
    rw: 'assets/images/flags/4x3/rw.svg',
    sa: 'assets/images/flags/4x3/sa.svg',
    sb: 'assets/images/flags/4x3/sb.svg',
    sc: 'assets/images/flags/4x3/sc.svg',
    sd: 'assets/images/flags/4x3/sd.svg',
    se: 'assets/images/flags/4x3/se.svg',
    sg: 'assets/images/flags/4x3/sg.svg',
    sh: 'assets/images/flags/4x3/sh.svg',
    si: 'assets/images/flags/4x3/si.svg',
    sj: 'assets/images/flags/4x3/sj.svg',
    sk: 'assets/images/flags/4x3/sk.svg',
    'sl-og': 'assets/images/flags/4x3/sl-og.svg',
    sl: 'assets/images/flags/4x3/sl.svg',
    sm: 'assets/images/flags/4x3/sm.svg',
    sn: 'assets/images/flags/4x3/sn.svg',
    so: 'assets/images/flags/4x3/so.svg',
    sr: 'assets/images/flags/4x3/sr.svg',
    ss: 'assets/images/flags/4x3/ss.svg',
    st: 'assets/images/flags/4x3/st.svg',
    sv: 'assets/images/flags/4x3/sv.svg',
    sx: 'assets/images/flags/4x3/sx.svg',
    sy: 'assets/images/flags/4x3/sy.svg',
    sz: 'assets/images/flags/4x3/sz.svg',
    tc: 'assets/images/flags/4x3/tc.svg',
    td: 'assets/images/flags/4x3/td.svg',
    tf: 'assets/images/flags/4x3/tf.svg',
    tg: 'assets/images/flags/4x3/tg.svg',
    th: 'assets/images/flags/4x3/th.svg',
    tj: 'assets/images/flags/4x3/tj.svg',
    tk: 'assets/images/flags/4x3/tk.svg',
    tl: 'assets/images/flags/4x3/tl.svg',
    tm: 'assets/images/flags/4x3/tm.svg',
    tn: 'assets/images/flags/4x3/tn.svg',
    to: 'assets/images/flags/4x3/to.svg',
    tr: 'assets/images/flags/4x3/tr.svg',
    tt: 'assets/images/flags/4x3/tt.svg',
    tv: 'assets/images/flags/4x3/tv.svg',
    tw: 'assets/images/flags/4x3/tw.svg',
    tz: 'assets/images/flags/4x3/tz.svg',
    ua: 'assets/images/flags/4x3/ua.svg',
    ug: 'assets/images/flags/4x3/ug.svg',
    um: 'assets/images/flags/4x3/um.svg',
    un: 'assets/images/flags/4x3/un.svg',
    us: 'assets/images/flags/4x3/us.svg',
    uy: 'assets/images/flags/4x3/uy.svg',
    uz: 'assets/images/flags/4x3/uz.svg',
    va: 'assets/images/flags/4x3/va.svg',
    vc: 'assets/images/flags/4x3/vc.svg',
    ve: 'assets/images/flags/4x3/ve.svg',
    vg: 'assets/images/flags/4x3/vg.svg',
    vi: 'assets/images/flags/4x3/vi.svg',
    vn: 'assets/images/flags/4x3/vn.svg',
    vu: 'assets/images/flags/4x3/vu.svg',
    wa: 'assets/images/flags/4x3/wa.svg',
    wf: 'assets/images/flags/4x3/wf.svg',
    ws: 'assets/images/flags/4x3/ws.svg',
    ye: 'assets/images/flags/4x3/ye.svg',
    yt: 'assets/images/flags/4x3/yt.svg',
    za: 'assets/images/flags/4x3/za.svg',
    zm: 'assets/images/flags/4x3/zm.svg',
    zw: 'assets/images/flags/4x3/zw.svg',
    zz: 'assets/images/flags/4x3/zz.svg',
  },
  
});
